# Generated by Django 3.0.5 on 2020-04-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200430_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='no_accepted',
        ),
        migrations.RemoveField(
            model_name='request',
            name='no_rejected',
        ),
    ]
