# Generated by Django 3.0.5 on 2020-05-01 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('post_id', models.IntegerField(default=-1)),
                ('com', models.TextField(max_length=300)),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('comment_id', models.IntegerField(default=-1)),
                ('reply_to', models.TextField(max_length=300)),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
